# -*- coding: utf-8 -*-
"""chunk.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FlpWLcTioRgkCQsajypA0z6D4LEgNxLO
"""

from sentence_transformers import SentenceTransformer
import json
from pathlib import Path
import numpy as np

from google.colab import files

uploaded = files.upload()  # Select your local JSON
json_file = list(uploaded.keys())[0]

chunks = []

with open(json_file, "r", encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if line:  # skip empty lines
            chunks.append(json.loads(line))

print(f"Loaded {len(chunks)} chunks.")

model = SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2')

# Generate embeddings
for chunk in chunks:
    chunk['embedding'] = model.encode(chunk['text']).tolist()  # convert to list for JSON

# Save the chunks with embeddings as JSONL
output_path = "chunks_with_embeddings.jsonl"
with open(output_path, "w", encoding="utf-8") as f:
    for chunk in chunks:
        f.write(json.dumps(chunk) + "\n")

print("Embeddings created and saved successfully!")

files.download(output_path)